export const fr = {
  langName: "Français",
  skip: "Aller au contenu",
  nav: {
    home: "Accueil",
    yacht: "Le yacht",
    gallery: "Galerie",
    place: "Ladeuze",
    rates: "Tarifs",
    faq: "FAQ",
    book: "Réserver",
  },
  hero: {
    eyebrow: "Ladeuze · Hainaut",
    title: "L'évasion",
    lead: "Dormir à bord, amarré au canal.",
    address: "Grande Drève 1 · 7950 Ladeuze",
    chips: ["Jusqu'à 6 voyageurs", "3 chambres", "Pont & jardin", "Parking privé"],
    cta: "Voir le calendrier",
    secondary: "Découvrir le yacht",
  },
  yacht: {
    kicker: "Le yacht",
    title: "Un logement entier, au fil de l'eau.",
    body: "L'évasion est un yacht-gîte amarré à la halte nautique de Ladeuze. Trois chambres, deux salles de bains, salon et cuisine équipée dans environ 54 m². Le pont couvert et la pelouse donnent sur le canal. Le bateau ne navigue pas : vous venez y ralentir.",
    facts: [
      { label: "Couchages", value: "2 doubles + 1 superposé" },
      { label: "Capacité", value: "2 à 6 voyageurs" },
      { label: "Salles de bains", value: "2 douches" },
      { label: "Séjour", value: "À partir de 2 nuits" },
    ],
  },
  amenities: {
    kicker: "À bord",
    title: "Tout est déjà là.",
    items: [
      { title: "Cuisine équipée", text: "Plaque, frigo, micro-ondes, cafetière et vaisselle." },
      { title: "Climatisation", text: "Pour les soirées chaudes comme pour les nuits fraîches." },
      { title: "Wi-Fi", text: "Connexion incluse dans tout le yacht." },
      { title: "Salon & écran", text: "Un vrai séjour, avec la vue sur l'eau." },
      { title: "Pont & jardin", text: "Fauteuils sur le pont, table dehors, pelouse le long du quai." },
      { title: "Linge fourni", text: "Draps et serviettes sont prêts à l'arrivée." },
      { title: "Parking privé", text: "Une place sur place, sans supplément." },
      { title: "Enfants bienvenus", text: "Lit bébé sur demande, 15 € par nuit." },
    ],
  },
  gallery: {
    kicker: "Galerie",
    title: "Le canal, le pont, les chambres.",
    lead: "Le yacht tel qu'il est amarré à Ladeuze, de jour comme le soir.",
    more: "Voir plus de photos",
    less: "Voir moins",
    close: "Fermer",
    prev: "Photo précédente",
    next: "Photo suivante",
  },
  place: {
    kicker: "Ladeuze & les environs",
    title: "Le calme du canal, Pairi Daiza tout près.",
    body: "Amarré Grande Drève à Ladeuze (Chièvres). Le chemin de halage part devant la pelouse. Chièvres et Pairi Daiza sont à quelques minutes ; Charleroi-Bruxelles-Sud à environ une heure.",
    highlights: [
      {
        title: "Pairi Daiza",
        text: "Le parc animalier est à une courte route. Idéal pour une journée en famille.",
        cta: "Site Pairi Daiza",
        href: "https://www.pairidaiza.eu/",
        image: "/around/pairi-daiza.jpg",
        alt: "Allée arborée à Pairi Daiza",
      },
      {
        title: "Chemin de halage",
        text: "Balades à pied ou à vélo le long de l'eau, dès le quai du yacht.",
        cta: "Voir sur la carte",
        href: "https://www.google.com/maps?q=50.56945,3.770154",
        image: "/photos/08.jpg",
        alt: "Le canal et le chemin de halage à Ladeuze",
      },
      {
        title: "Halte & jardin",
        text: "Pelouse, table dehors et pont couvert pour profiter du canal au calme.",
        cta: "Voir le yacht",
        href: "/#yacht",
        image: "/photos/09.jpg",
        alt: "Pelouse et pont arrière du yacht",
      },
      {
        title: "Office du tourisme",
        text: "Balades, patrimoine et idées de sorties autour de Chièvres.",
        cta: "Site de l'OT",
        href: "https://otchievres.wixsite.com/site-otc",
        image: "/photos/06.jpg",
        alt: "Halte nautique de Ladeuze",
      },
    ],
    map: "Voir sur Google Maps",
  },
  rates: {
    kicker: "Tarifs",
    title: "Un tarif unique par nuit.",
    note: "Prix pour le yacht entier, toute l'année. Le lit bébé est en option.",
    night: "Par nuit",
    nightHint: "Yacht entier · jusqu'à 6 voyageurs",
    rows: [
      { label: "Lit bébé, par nuit", value: "15 €" },
      { label: "Arrivée", value: "16:00 – 20:00" },
      { label: "Départ", value: "08:00 – 11:00" },
      { label: "Acompte", value: "15 %" },
    ],
    includedTitle: "Inclus",
    included: ["Logement entier jusqu'à 6 personnes", "Wi-Fi et climatisation", "Linge de lit et serviettes", "Parking privé", "Cuisine équipée"],
    practicalTitle: "À savoir",
    practical: ["Réservation uniquement sur ce site", "Non-fumeur · animaux non admis", "Acompte 15 % après confirmation", "Solde 60 jours avant l'arrivée"],
  },
  steps: {
    kicker: "Calendrier",
    title: "Disponibilités et réservation",
    lead: "Choisissez vos dates sur le calendrier. Le total s'affiche tout de suite, puis vous envoyez la demande.",
    items: [
      { title: "Choisir les dates", text: "Arrivée, puis départ." },
      { title: "Voir le tarif", text: "Nuit × prix unique." },
      { title: "Envoyer la demande", text: "Un e-mail part vers vous et vers l'hôte." },
      { title: "Acompte 15 %", text: "Après confirmation, paiement par carte." },
      { title: "Solde à 60 jours", text: "Le reste aussi par carte, deux mois avant." },
    ],
  },
  faq: {
    kicker: "FAQ",
    title: "Les questions qui reviennent.",
    items: [
      {
        q: "Le yacht navigue-t-il pendant le séjour ?",
        a: "Non. Il est amarré à la halte nautique de Ladeuze. Vous logez à bord, au calme, sans croisière.",
      },
      {
        q: "Combien de personnes peuvent dormir à bord ?",
        a: "Jusqu'à 6 voyageurs : deux chambres avec lit double et une chambre avec lits superposés. Il y a deux salles de bains.",
      },
      {
        q: "Quelle est la durée minimale ?",
        a: "Le séjour compte au moins 2 nuits, et au maximum 21 nuits. Le tarif est unique, par nuit, pour le yacht entier.",
      },
      {
        q: "Comment se passe le paiement ?",
        a: "Vous envoyez une demande sur ce site : un e-mail part vers vous et vers l'hôte. Après confirmation, un acompte de 15 % se règle par carte (Stripe). Le solde est dû 60 jours avant l'arrivée, également par carte.",
      },
      {
        q: "Les animaux sont-ils acceptés ?",
        a: "Non. Le yacht est non-fumeur et les animaux ne sont pas admis.",
      },
      {
        q: "À quelle heure arrive-t-on ?",
        a: "Entre 16:00 et 20:00. Le départ se fait entre 08:00 et 11:00.",
      },
      {
        q: "Y a-t-il un parking ?",
        a: "Oui, un parking privé est disponible sur place, sans supplément.",
      },
    ],
  },
  footer: {
    blurb: "Yacht-gîte amarré à la halte nautique de Ladeuze.",
    explore: "Explorer",
    follow: "Suivre",
    legal: "Mentions légales",
    privacy: "Confidentialité",
    cookies: "Cookies",
    terms: "Conditions de séjour",
    admin: "Espace admin",
    facebook: "Facebook",
    instagram: "Instagram",
    credit: "Site réalisé par LD Media — Agence de communication à Ath",
    creditHref: "https://ldmedia.be/",
  },
  cookie: {
    title: "Cookies & confidentialité",
    text: "Nous utilisons uniquement des cookies essentiels pour mémoriser votre langue et votre choix de consentement. Aucune publicité n'est diffusée. Paiements éventuels via Stripe.",
    accept: "Accepter",
    more: "En savoir plus",
  },
  float: "Réserver",
  form: {
    title: "Réserver le yacht",
    datesTitle: "Dates et tarif",
    detailsTitle: "Vos coordonnées",
    lead: "Choisissez l'arrivée, puis le départ. Le total s'affiche tout de suite.",
    detailsLead: "Nous confirmons les dates par e-mail, puis l'acompte se règle par carte.",
    checkIn: "Arrivée",
    checkOut: "Départ",
    guests: "Voyageurs",
    adults: "Adultes",
    children: "Enfants",
    country: "Pays",
    legend: { free: "Libre", booked: "Réservé", pending: "En attente", depart: "Jour de départ" },
    discount: "Remise durée",
    total: "Total du séjour",
    deposit: "Acompte 15 %",
    balance: "Solde",
    terms: "J'ai lu les conditions : acompte non remboursable hors force majeure, solde 60 jours avant l'arrivée.",
    continue: "Voir le tarif et continuer",
    back: "Retour aux dates",
    cot: "Lit bébé (15 € / nuit)",
    cotLine: "Lit bébé",
    options: "Options",
    name: "Nom",
    email: "E-mail",
    phone: "Téléphone",
    message: "Message",
    messageHint: "Heure d'arrivée, petit-déjeuner, question…",
    submit: "Envoyer la demande",
    sending: "Envoi…",
    estimate: "Estimation",
    nights: "nuits",
    night: "nuit",
    perNight: "par nuit",
    unavailable: "Ces nuits ne sont plus libres.",
    bookedHint: "Les nuits grisées sont déjà demandées ou confirmées.",
    clear: "Effacer les dates",
    errors: {
      dates: "Choisissez une arrivée et un départ.",
      past: "L'arrivée ne peut pas être dans le passé.",
      order: "Le départ doit être après l'arrivée.",
      min: "Le séjour compte au moins 2 nuits.",
      terms: "Acceptez les conditions du séjour pour envoyer la demande.",
      max: "Le séjour est limité à 21 nuits.",
      guests: "Indiquez entre 1 et 6 voyageurs.",
      contact: "Nom, e-mail et téléphone sont nécessaires.",
      email: "Cet e-mail ne semble pas valide.",
      conflict: "Ces dates viennent d'être prises. Choisissez-en d'autres.",
      server: "L'envoi n'a pas abouti. Réessayez ou appelez-nous.",
    },
  },
  thanks: {
    kicker: "Demande envoyée",
    title: "Nous avons bien reçu vos dates.",
    body: "Votre demande est en attente de confirmation. Ces nuits ne sont plus proposées à quelqu'un d'autre tant que l'hôte n'a pas répondu.",
    ref: "Référence",
    pending: "En attente",
    confirmed: "Confirmée",
    declined: "Refusée",
    cancelled: "Annulée",
    unpaid: "Acompte à venir",
    deposit_link_sent: "Lien d'acompte envoyé",
    deposit_paid: "Acompte payé",
    balance_link_sent: "Lien de solde envoyé",
    paid: "Soldée",
    missing: "Cette réservation est introuvable.",
    back: "Retour à l'accueil",
  },
  legal: {
    title: "Mentions légales",
    sections: [
      {
        title: "Éditeur",
        body: "L'évasion — hébergement touristique. Exploitant : Grégory Nicodème. Numéro d'enregistrement : BE1023606158. Grande Drève 1, 7950 Ladeuze (Chièvres), Belgique. E-mail : evasionyacht@hotmail.com. Téléphone : +32 491 86 58 09.",
      },
      {
        title: "Hébergement du site",
        body: "Le site peut être publié sur Vercel Inc. Les réservations sont enregistrées côté serveur, dans le fichier de réservations de l'application.",
      },
      {
        title: "Propriété intellectuelle",
        body: "Textes, photos et éléments graphiques du site sont protégés. Toute reproduction non autorisée est interdite, sauf usage privé.",
      },
      {
        title: "Responsabilité",
        body: "Les informations sont fournies de bonne foi. L'éditeur ne peut être tenu responsable d'une indisponibilité temporaire du site ou d'erreurs de saisie lors d'une demande.",
      },
    ],
  },
  pages: {
    legal: {
      title: "Mentions légales",
      sections: [
        {
          title: "Éditeur",
          body: "L'évasion — hébergement touristique. Exploitant : Grégory Nicodème. Numéro d'enregistrement : BE1023606158. Grande Drève 1, 7950 Ladeuze (Chièvres), Belgique. E-mail : evasionyacht@hotmail.com. Téléphone : +32 491 86 58 09.",
        },
        {
          title: "Hébergement du site",
          body: "Le site peut être publié sur Vercel Inc. Les réservations sont enregistrées côté serveur, dans le fichier de réservations de l'application.",
        },
        {
          title: "Propriété intellectuelle",
          body: "Textes, photos et éléments graphiques du site sont protégés. Toute reproduction non autorisée est interdite, sauf usage privé.",
        },
        {
          title: "Responsabilité",
          body: "Les informations sont fournies de bonne foi. L'éditeur ne peut être tenu responsable d'une indisponibilité temporaire du site ou d'erreurs de saisie lors d'une demande.",
        },
      ],
    },
    privacy: {
      title: "Politique de confidentialité",
      sections: [
        {
          title: "Responsable du traitement",
          body: "Grégory Nicodème — L'évasion, Grande Drève 1, 7950 Ladeuze. Contact : evasionyacht@hotmail.com / +32 491 86 58 09.",
        },
        {
          title: "Données collectées",
          body: "Via le formulaire de réservation : nom, e-mail, téléphone, pays, dates, nombre de voyageurs, message éventuel et options (lit bébé). Ces données servent uniquement à traiter et confirmer le séjour, et à gérer l'acompte / le solde.",
        },
        {
          title: "Base légale & durée",
          body: "Exécution de mesures précontractuelles et contractuelles (demande de séjour). Conservation pendant la durée nécessaire à la gestion de la réservation et aux obligations comptables éventuelles.",
        },
        {
          title: "Destinataires",
          body: "L'exploitant du gîte. En cas de paiement en ligne, Stripe traite les données de paiement (carte) selon ses propres conditions. Aucune revente à des tiers à des fins commerciales.",
        },
        {
          title: "Vos droits",
          body: "Conformément au RGPD, vous pouvez demander l'accès, la rectification, l'effacement ou la limitation du traitement de vos données, et introduire une réclamation auprès de l'Autorité de protection des données (APD — Belgique).",
        },
      ],
    },
    cookies: {
      title: "Politique de cookies",
      sections: [
        {
          title: "Ce que nous utilisons",
          body: "Cookies et stockage local strictement nécessaires : langue choisie (localStorage) et choix de consentement cookies. Ils ne servent pas à la publicité ni au profilage.",
        },
        {
          title: "Paiement Stripe",
          body: "Si vous payez un acompte ou un solde, Stripe peut déposer ses propres cookies techniques sur les pages de paiement. Consultez la politique Stripe pour plus de détails.",
        },
        {
          title: "Gestion",
          body: "Vous pouvez effacer les données du navigateur à tout moment. Refuser les cookies non essentiels n'empêche pas la consultation du site ; le formulaire de réservation reste utilisable.",
        },
      ],
    },
    terms: {
      title: "Conditions de séjour",
      sections: [
        {
          title: "Réservation",
          body: "La demande en ligne bloque provisoirement les dates. Le séjour devient ferme après confirmation par l'hôte. Capacité maximale : 6 voyageurs. Séjour de 2 à 21 nuits.",
        },
        {
          title: "Tarif & paiement",
          body: "Tarif unique par nuit pour le yacht entier. Acompte de 15 % après confirmation, payable par carte (Stripe). Solde dû 60 jours avant l'arrivée, également par carte. Hors force majeure, l'acompte n'est pas remboursable.",
        },
        {
          title: "Arrivée & départ",
          body: "Arrivée entre 16:00 et 20:00. Départ entre 08:00 et 11:00. Autre horaire sur demande écrite.",
        },
        {
          title: "Règlement intérieur",
          body: "Logement non-fumeur. Animaux non admis. Le yacht ne navigue pas pendant le séjour. Respect du voisinage et des installations à bord.",
        },
        {
          title: "Annulation",
          body: "Toute annulation doit être notifiée par e-mail. Selon le délai et le motif (y compris force majeure), l'hôte précise le traitement de l'acompte et du solde déjà versés.",
        },
      ],
    },
  },
  admin: {
    title: "Espace admin",
    lead: "Demandes, e-mails, acompte Stripe et solde.",
    password: "Mot de passe",
    enter: "Entrer",
    badPassword: "Mot de passe incorrect.",
    logout: "Quitter",
    empty: "Aucune réservation pour le moment.",
    stripeOn: "Stripe est configuré. Vous pouvez créer un lien de paiement.",
    stripeOff: "Stripe n'est pas encore branché. Ajoutez STRIPE_SECRET_KEY pour activer les liens.",
    confirm: "Confirmer",
    decline: "Refuser",
    cancel: "Annuler",
    paid: "Marquer payé",
    link: "Lien Stripe",
    copy: "Copier le lien",
    copied: "Lien copié",
    amount: "Montant (€)",
    saveAmount: "Enregistrer le montant",
    blockTitle: "Bloquer des dates",
    blockLead: "Pour une réservation prise ailleurs, ou une indisponibilité.",
    block: "Bloquer",
    note: "Note",
    statuses: {
      pending: "En attente",
      confirmed: "Confirmée",
      declined: "Refusée",
      cancelled: "Annulée",
    },
    payments: {
      unpaid: "Non payé",
      deposit_link_sent: "Lien d'acompte",
      deposit_paid: "Acompte payé",
      balance_link_sent: "Lien de solde",
      paid: "Soldé",
    },
    depositLink: "Lien acompte",
    balanceLink: "Lien solde",
  },
};

export type Copy = typeof fr;

export const nl: Copy = {
  langName: "Nederlands",
  skip: "Naar de inhoud",
  nav: {
    home: "Home",
    yacht: "Het jacht",
    gallery: "Galerij",
    place: "Ladeuze",
    rates: "Tarieven",
    faq: "FAQ",
    book: "Reserveren",
  },
  hero: {
    eyebrow: "Ladeuze · Henegouwen",
    title: "L'évasion",
    lead: "Slapen aan boord, afgemeerd aan het kanaal.",
    address: "Grande Drève 1 · 7950 Ladeuze",
    chips: ["Tot 6 gasten", "3 slaapkamers", "Dek & tuin", "Privéparkeer"],
    cta: "Kalender bekijken",
    secondary: "Het jacht ontdekken",
  },
  yacht: {
    kicker: "Het jacht",
    title: "Een volledige woning, aan het water.",
    body: "L'évasion is een yacht-gîte afgemeerd aan de jachthaven van Ladeuze. Drie slaapkamers, twee badkamers, salon en ingerichte keuken in ongeveer 54 m². Het overdekte dek en het gras kijken uit op het kanaal. Het schip vaart niet: u komt vertragen.",
    facts: [
      { label: "Slaapplaatsen", value: "2 tweepersoons + 1 stapelbed" },
      { label: "Capaciteit", value: "2 tot 6 gasten" },
      { label: "Badkamers", value: "2 douches" },
      { label: "Verblijf", value: "Vanaf 2 nachten" },
    ],
  },
  amenities: {
    kicker: "Aan boord",
    title: "Alles staat klaar.",
    items: [
      { title: "Ingerichte keuken", text: "Kookplaat, koelkast, microgolf, koffiezet en vaatwerk." },
      { title: "Airconditioning", text: "Voor warme avonden en frisse nachten." },
      { title: "Wi-Fi", text: "Inbegrepen in het hele jacht." },
      { title: "Salon & scherm", text: "Een echte woonkamer, met zicht op het water." },
      { title: "Dek & tuin", text: "Zetels op het dek, tafel buiten, gras langs de kade." },
      { title: "Linnen voorzien", text: "Lakens en handdoeken liggen klaar." },
      { title: "Privéparkeer", text: "Een plaats ter plaatse, zonder toeslag." },
      { title: "Kinderen welkom", text: "Babybed op aanvraag, 15 € per nacht." },
    ],
  },
  gallery: {
    kicker: "Galerij",
    title: "Het kanaal, het dek, de kamers.",
    lead: "Het jacht zoals het in Ladeuze ligt, overdag en 's avonds.",
    more: "Meer foto's bekijken",
    less: "Minder tonen",
    close: "Sluiten",
    prev: "Vorige foto",
    next: "Volgende foto",
  },
  place: {
    kicker: "Ladeuze & de omgeving",
    title: "De rust van het kanaal, Pairi Daiza vlakbij.",
    body: "Afgemeerd aan de Grande Drève in Ladeuze (Chièvres). Het jaagpad begint voor het gras. Chièvres en Pairi Daiza zijn enkele minuten rijden; Brussels South Charleroi ongeveer een uur.",
    highlights: [
      {
        title: "Pairi Daiza",
        text: "Het dierenpark is een korte rit. Ideaal voor een gezinsdag.",
        cta: "Site Pairi Daiza",
        href: "https://www.pairidaiza.eu/",
        image: "/around/pairi-daiza.jpg",
        alt: "Laan in Pairi Daiza",
      },
      {
        title: "Jaagpad",
        text: "Wandelen of fietsen langs het water, vanaf de kade van het jacht.",
        cta: "Bekijk op de kaart",
        href: "https://www.google.com/maps?q=50.56945,3.770154",
        image: "/photos/08.jpg",
        alt: "Het kanaal en het jaagpad in Ladeuze",
      },
      {
        title: "Haven & tuin",
        text: "Gras, tafel buiten en overdekt dek om van het kanaal te genieten.",
        cta: "Het jacht bekijken",
        href: "/#yacht",
        image: "/photos/09.jpg",
        alt: "Gras en achterdek van het jacht",
      },
      {
        title: "Toeristische dienst",
        text: "Wandelingen, erfgoed en uitstappen rond Chièvres.",
        cta: "Website van de OT",
        href: "https://otchievres.wixsite.com/site-otc",
        image: "/photos/06.jpg",
        alt: "Jachthaven van Ladeuze",
      },
    ],
    map: "Bekijk op Google Maps",
  },
  rates: {
    kicker: "Tarieven",
    title: "Eén tarief per nacht.",
    note: "Prijs voor het hele jacht, het hele jaar. Babybed optioneel.",
    night: "Per nacht",
    nightHint: "Heel jacht · tot 6 gasten",
    rows: [
      { label: "Babybed, per nacht", value: "15 €" },
      { label: "Aankomst", value: "16:00 – 20:00" },
      { label: "Vertrek", value: "08:00 – 11:00" },
      { label: "Aanbetaling", value: "15 %" },
    ],
    includedTitle: "Inbegrepen",
    included: ["Volledige woning tot 6 personen", "Wi-Fi en airconditioning", "Bedlinnen en handdoeken", "Privéparkeer", "Ingerichte keuken"],
    practicalTitle: "Goed om te weten",
    practical: ["Enkel reserveren via deze site", "Rookvrij · geen huisdieren", "Aanbetaling 15 % na bevestiging", "Saldo 60 dagen voor aankomst"],
  },
  steps: {
    kicker: "Kalender",
    title: "Beschikbaarheid en reservatie",
    lead: "Kies uw data op de kalender. Het totaal verschijnt meteen, daarna stuurt u de aanvraag.",
    items: [
      { title: "Data kiezen", text: "Aankomst, daarna vertrek." },
      { title: "Tarief zien", text: "Nachten × uniek tarief." },
      { title: "Aanvraag sturen", text: "Een e-mail gaat naar u en naar de gastheer." },
      { title: "Aanbetaling 15 %", text: "Na bevestiging, betaling met kaart." },
      { title: "Saldo op 60 dagen", text: "De rest ook met kaart, twee maanden vooraf." },
    ],
  },
  faq: {
    kicker: "FAQ",
    title: "De vragen die terugkomen.",
    items: [
      {
        q: "Vaart het jacht tijdens het verblijf?",
        a: "Nee. Het ligt afgemeerd aan de jachthaven van Ladeuze. U logeert aan boord, in alle rust, zonder cruise.",
      },
      {
        q: "Hoeveel personen kunnen aan boord slapen?",
        a: "Tot 6 gasten: twee kamers met een tweepersoonsbed en een kamer met een stapelbed. Er zijn twee badkamers.",
      },
      {
        q: "Wat is de minimale verblijfsduur?",
        a: "Minstens 2 nachten, maximum 21. Het tarief is uniek, per nacht, voor het hele jacht.",
      },
      {
        q: "Hoe verloopt de betaling?",
        a: "U stuurt een aanvraag via deze site: een e-mail gaat naar u en naar de gastheer. Na bevestiging betaalt u 15 % aanbetaling met kaart (Stripe). Het saldo is verschuldigd 60 dagen voor aankomst, ook met kaart.",
      },
      {
        q: "Zijn huisdieren toegelaten?",
        a: "Nee. Het jacht is rookvrij en huisdieren zijn niet toegelaten.",
      },
      {
        q: "Hoe laat komen we aan?",
        a: "Tussen 16:00 en 20:00. Vertrek tussen 08:00 en 11:00.",
      },
      {
        q: "Is er parking?",
        a: "Ja, een privéparkeer is ter plaatse beschikbaar, zonder toeslag.",
      },
    ],
  },
  footer: {
    blurb: "Yacht-gîte afgemeerd aan de jachthaven van Ladeuze.",
    explore: "Ontdekken",
    follow: "Volgen",
    legal: "Wettelijke vermeldingen",
    privacy: "Privacy",
    cookies: "Cookies",
    terms: "Verblijfsvoorwaarden",
    admin: "Beheer",
    facebook: "Facebook",
    instagram: "Instagram",
    credit: "Site gemaakt door LD Media — Communicatiebureau in Ath",
    creditHref: "https://ldmedia.be/",
  },
  cookie: {
    title: "Cookies & privacy",
    text: "We gebruiken enkel essentiële cookies om uw taal en toestemming te onthouden. Geen reclame. Eventuele betalingen via Stripe.",
    accept: "Aanvaarden",
    more: "Meer info",
  },
  float: "Reserveren",
  form: {
    title: "Het jacht reserveren",
    datesTitle: "Data en tarief",
    detailsTitle: "Uw gegevens",
    lead: "Kies de aankomst, daarna het vertrek. Het totaal verschijnt meteen.",
    detailsLead: "We bevestigen de data per e-mail, daarna betaalt u de aanbetaling met kaart.",
    checkIn: "Aankomst",
    checkOut: "Vertrek",
    guests: "Gasten",
    adults: "Volwassenen",
    children: "Kinderen",
    country: "Land",
    legend: { free: "Vrij", booked: "Gereserveerd", pending: "In afwachting", depart: "Vertrekdag" },
    discount: "Verblijfskorting",
    total: "Totaal van het verblijf",
    deposit: "Aanbetaling 15 %",
    balance: "Saldo",
    terms: "Ik heb de voorwaarden gelezen: de aanbetaling is niet terugbetaalbaar buiten overmacht, saldo 60 dagen voor aankomst.",
    continue: "Tarief bekijken en verdergaan",
    back: "Terug naar de data",
    cot: "Babybed (15 € / nacht)",
    cotLine: "Babybed",
    options: "Opties",
    name: "Naam",
    email: "E-mail",
    phone: "Telefoon",
    message: "Bericht",
    messageHint: "Aankomstuur, ontbijt, vraag…",
    submit: "Aanvraag versturen",
    sending: "Verzenden…",
    estimate: "Raming",
    nights: "nachten",
    night: "nacht",
    perNight: "per nacht",
    unavailable: "Deze nachten zijn niet meer vrij.",
    bookedHint: "Grijze nachten zijn al aangevraagd of bevestigd.",
    clear: "Data wissen",
    errors: {
      dates: "Kies een aankomst en een vertrek.",
      past: "De aankomst kan niet in het verleden liggen.",
      order: "Het vertrek moet na de aankomst liggen.",
      min: "Het verblijf telt minstens 2 nachten.",
      terms: "Aanvaard de verblijfsvoorwaarden om de aanvraag te versturen.",
      max: "Het verblijf is beperkt tot 21 nachten.",
      guests: "Geef 1 tot 6 gasten op.",
      contact: "Naam, e-mail en telefoon zijn nodig.",
      email: "Dit e-mailadres lijkt ongeldig.",
      conflict: "Deze data zijn net genomen. Kies andere.",
      server: "Het versturen is mislukt. Probeer opnieuw of bel ons.",
    },
  },
  thanks: {
    kicker: "Aanvraag verstuurd",
    title: "We hebben uw data goed ontvangen.",
    body: "Uw aanvraag wacht op bevestiging. Deze nachten worden niet meer aan iemand anders aangeboden zolang de gastheer niet heeft geantwoord.",
    ref: "Referentie",
    pending: "In afwachting",
    confirmed: "Bevestigd",
    declined: "Geweigerd",
    cancelled: "Geannuleerd",
    unpaid: "Aanbetaling volgt",
    deposit_link_sent: "Link aanbetaling verstuurd",
    deposit_paid: "Aanbetaling betaald",
    balance_link_sent: "Link saldo verstuurd",
    paid: "Voldaan",
    missing: "Deze reservatie werd niet gevonden.",
    back: "Terug naar home",
  },
  legal: fr.legal,
  pages: fr.pages,
  admin: fr.admin,
};

export const en: Copy = {
  langName: "English",
  skip: "Skip to content",
  nav: {
    home: "Home",
    yacht: "The yacht",
    gallery: "Gallery",
    place: "Ladeuze",
    rates: "Rates",
    faq: "FAQ",
    book: "Book",
  },
  hero: {
    eyebrow: "Ladeuze · Hainaut",
    title: "L'évasion",
    lead: "Sleep on board, moored on the canal.",
    address: "Grande Drève 1 · 7950 Ladeuze",
    chips: ["Up to 6 guests", "3 bedrooms", "Deck & garden", "Private parking"],
    cta: "See the calendar",
    secondary: "Discover the yacht",
  },
  yacht: {
    kicker: "The yacht",
    title: "An entire home, by the water.",
    body: "L'évasion is a yacht guesthouse moored at the Ladeuze harbour. Three bedrooms, two bathrooms, lounge and fitted kitchen in about 54 m². The covered deck and the lawn face the canal. The boat does not sail: you come to slow down.",
    facts: [
      { label: "Beds", value: "2 doubles + 1 bunk" },
      { label: "Capacity", value: "2 to 6 guests" },
      { label: "Bathrooms", value: "2 showers" },
      { label: "Stay", value: "From 2 nights" },
    ],
  },
  amenities: {
    kicker: "On board",
    title: "Everything is already here.",
    items: [
      { title: "Fitted kitchen", text: "Hob, fridge, microwave, coffee maker and crockery." },
      { title: "Air conditioning", text: "For warm evenings and cool nights." },
      { title: "Wi-Fi", text: "Included throughout the yacht." },
      { title: "Lounge & screen", text: "A proper living room, looking onto the water." },
      { title: "Deck & garden", text: "Chairs on deck, a table outside, lawn along the quay." },
      { title: "Linen included", text: "Sheets and towels are ready on arrival." },
      { title: "Private parking", text: "A space on site, at no extra charge." },
      { title: "Children welcome", text: "Cot on request, €15 per night." },
    ],
  },
  gallery: {
    kicker: "Gallery",
    title: "The canal, the deck, the rooms.",
    lead: "The yacht as it sits in Ladeuze, by day and in the evening.",
    more: "See more photos",
    less: "See less",
    close: "Close",
    prev: "Previous photo",
    next: "Next photo",
  },
  place: {
    kicker: "Ladeuze & around",
    title: "Quiet canal water, Pairi Daiza nearby.",
    body: "Moored on Grande Drève in Ladeuze (Chièvres). The towpath starts by the lawn. Chièvres and Pairi Daiza are a few minutes away; Brussels South Charleroi about an hour.",
    highlights: [
      {
        title: "Pairi Daiza",
        text: "The animal park is a short drive away. Ideal for a family day out.",
        cta: "Pairi Daiza website",
        href: "https://www.pairidaiza.eu/",
        image: "/around/pairi-daiza.jpg",
        alt: "Tree-lined path at Pairi Daiza",
      },
      {
        title: "Towpath",
        text: "Walk or cycle along the water, right from the yacht quay.",
        cta: "See on the map",
        href: "https://www.google.com/maps?q=50.56945,3.770154",
        image: "/photos/08.jpg",
        alt: "The canal and towpath in Ladeuze",
      },
      {
        title: "Harbour & garden",
        text: "Lawn, outdoor table and covered deck to enjoy the canal quietly.",
        cta: "See the yacht",
        href: "/#yacht",
        image: "/photos/09.jpg",
        alt: "Lawn and aft deck of the yacht",
      },
      {
        title: "Tourist office",
        text: "Walks, heritage and day-trip ideas around Chièvres.",
        cta: "Tourist office site",
        href: "https://otchievres.wixsite.com/site-otc",
        image: "/photos/06.jpg",
        alt: "Ladeuze harbour",
      },
    ],
    map: "Open in Google Maps",
  },
  rates: {
    kicker: "Rates",
    title: "One rate per night.",
    note: "Price for the whole yacht, year-round. Cot optional.",
    night: "Per night",
    nightHint: "Entire yacht · up to 6 guests",
    rows: [
      { label: "Cot, per night", value: "€15" },
      { label: "Arrival", value: "16:00 – 20:00" },
      { label: "Departure", value: "08:00 – 11:00" },
      { label: "Deposit", value: "15%" },
    ],
    includedTitle: "Included",
    included: ["Entire home for up to 6 guests", "Wi-Fi and air conditioning", "Bed linen and towels", "Private parking", "Fitted kitchen"],
    practicalTitle: "Good to know",
    practical: ["Book only on this site", "Non-smoking · no pets", "15% deposit after confirmation", "Balance 60 days before arrival"],
  },
  steps: {
    kicker: "Calendar",
    title: "Availability and booking",
    lead: "Pick your dates on the calendar. The total appears at once, then you send the request.",
    items: [
      { title: "Choose the dates", text: "Arrival, then departure." },
      { title: "See the rate", text: "Nights × single rate." },
      { title: "Send the request", text: "An email goes to you and to the host." },
      { title: "15% deposit", text: "After confirmation, pay by card." },
      { title: "Balance at 60 days", text: "The rest by card, two months ahead." },
    ],
  },
  faq: {
    kicker: "FAQ",
    title: "The questions that come back.",
    items: [
      {
        q: "Does the yacht sail during the stay?",
        a: "No. It is moored at the Ladeuze harbour. You stay on board, quietly, with no cruise.",
      },
      {
        q: "How many people can sleep on board?",
        a: "Up to 6 guests: two rooms with a double bed and one room with a bunk bed. There are two bathrooms.",
      },
      {
        q: "What is the minimum stay?",
        a: "At least 2 nights, and at most 21. The rate is a single nightly price for the whole yacht.",
      },
      {
        q: "How does payment work?",
        a: "You send a request on this site: an email goes to you and to the host. After confirmation, a 15% deposit is paid by card (Stripe). The balance is due 60 days before arrival, also by card.",
      },
      {
        q: "Are pets allowed?",
        a: "No. The yacht is non-smoking and pets are not admitted.",
      },
      {
        q: "What time do we arrive?",
        a: "Between 16:00 and 20:00. Departure is between 08:00 and 11:00.",
      },
      {
        q: "Is there parking?",
        a: "Yes, private parking is available on site, at no extra charge.",
      },
    ],
  },
  footer: {
    blurb: "A yacht guesthouse moored at the Ladeuze harbour.",
    explore: "Explore",
    follow: "Follow",
    legal: "Legal notice",
    privacy: "Privacy",
    cookies: "Cookies",
    terms: "Stay conditions",
    admin: "Admin",
    facebook: "Facebook",
    instagram: "Instagram",
    credit: "Website by LD Media — Communication agency in Ath",
    creditHref: "https://ldmedia.be/",
  },
  cookie: {
    title: "Cookies & privacy",
    text: "We only use essential cookies to remember your language and consent choice. No advertising. Payments, if any, go through Stripe.",
    accept: "Accept",
    more: "Learn more",
  },
  float: "Book",
  form: {
    title: "Book the yacht",
    datesTitle: "Dates and rate",
    detailsTitle: "Your details",
    lead: "Choose arrival, then departure. The total appears at once.",
    detailsLead: "We confirm the dates by email, then the deposit is paid by card.",
    checkIn: "Arrival",
    checkOut: "Departure",
    guests: "Guests",
    adults: "Adults",
    children: "Children",
    country: "Country",
    legend: { free: "Available", booked: "Booked", pending: "Awaiting confirmation", depart: "Departure day" },
    discount: "Length discount",
    total: "Stay total",
    deposit: "15% deposit",
    balance: "Balance",
    terms: "I have read the conditions: the deposit is non-refundable except for force majeure, balance due 60 days before arrival.",
    continue: "See the rate and continue",
    back: "Back to dates",
    cot: "Cot (€15 / night)",
    cotLine: "Cot",
    options: "Options",
    name: "Name",
    email: "Email",
    phone: "Phone",
    message: "Message",
    messageHint: "Arrival time, breakfast, a question…",
    submit: "Send the request",
    sending: "Sending…",
    estimate: "Estimate",
    nights: "nights",
    night: "night",
    perNight: "per night",
    unavailable: "These nights are no longer free.",
    bookedHint: "Grey nights are already requested or confirmed.",
    clear: "Clear dates",
    errors: {
      dates: "Choose an arrival and a departure.",
      past: "Arrival cannot be in the past.",
      order: "Departure must be after arrival.",
      min: "The stay is at least 2 nights.",
      terms: "Accept the stay conditions to send the request.",
      max: "The stay is limited to 21 nights.",
      guests: "Enter between 1 and 6 guests.",
      contact: "Name, email and phone are required.",
      email: "This email does not look valid.",
      conflict: "These dates were just taken. Please choose others.",
      server: "The request did not go through. Try again or call us.",
    },
  },
  thanks: {
    kicker: "Request sent",
    title: "We have your dates.",
    body: "Your request is waiting for confirmation. These nights are no longer offered to anyone else until the host replies.",
    ref: "Reference",
    pending: "Pending",
    confirmed: "Confirmed",
    declined: "Declined",
    cancelled: "Cancelled",
    unpaid: "Deposit to follow",
    deposit_link_sent: "Deposit link sent",
    deposit_paid: "Deposit paid",
    balance_link_sent: "Balance link sent",
    paid: "Paid in full",
    missing: "This booking could not be found.",
    back: "Back home",
  },
  legal: {
    title: "Legal notice",
    sections: [
      {
        title: "Publisher",
        body: "L'évasion — tourist accommodation. Operator: Grégory Nicodème. Registration number: BE1023606158. Grande Drève 1, 7950 Ladeuze (Chièvres), Belgium. Email: evasionyacht@hotmail.com. Phone: +32 491 86 58 09.",
      },
      {
        title: "Hosting",
        body: "The site may be published on Vercel Inc. Bookings are stored on the server, in the application's reservation file.",
      },
      {
        title: "Intellectual property",
        body: "Texts, photos and graphic elements are protected. Unauthorised reproduction is forbidden, except for private use.",
      },
      {
        title: "Liability",
        body: "Information is provided in good faith. The publisher is not liable for temporary unavailability of the site or typing errors in a request.",
      },
    ],
  },
  pages: {
    legal: {
      title: "Legal notice",
      sections: [
        {
          title: "Publisher",
          body: "L'évasion — tourist accommodation. Operator: Grégory Nicodème. Registration number: BE1023606158. Grande Drève 1, 7950 Ladeuze (Chièvres), Belgium. Email: evasionyacht@hotmail.com. Phone: +32 491 86 58 09.",
        },
        {
          title: "Hosting",
          body: "The site may be published on Vercel Inc. Bookings are stored on the server, in the application's reservation file.",
        },
        {
          title: "Intellectual property",
          body: "Texts, photos and graphic elements are protected. Unauthorised reproduction is forbidden, except for private use.",
        },
        {
          title: "Liability",
          body: "Information is provided in good faith. The publisher is not liable for temporary unavailability of the site or typing errors in a request.",
        },
      ],
    },
    privacy: {
      title: "Privacy policy",
      sections: [
        {
          title: "Data controller",
          body: "Grégory Nicodème — L'évasion, Grande Drève 1, 7950 Ladeuze. Contact: evasionyacht@hotmail.com / +32 491 86 58 09.",
        },
        {
          title: "Data collected",
          body: "Via the booking form: name, email, phone, country, dates, number of guests, optional message and options (cot). Used only to process and confirm the stay and manage deposit / balance payments.",
        },
        {
          title: "Legal basis & retention",
          body: "Pre-contractual and contractual steps for a stay request. Kept for as long as needed to manage the booking and any accounting duties.",
        },
        {
          title: "Recipients",
          body: "The guesthouse operator. For online payments, Stripe processes card data under its own terms. No sale to third parties for marketing.",
        },
        {
          title: "Your rights",
          body: "Under the GDPR you may request access, rectification, erasure or restriction, and lodge a complaint with the Belgian Data Protection Authority (APD).",
        },
      ],
    },
    cookies: {
      title: "Cookie policy",
      sections: [
        {
          title: "What we use",
          body: "Strictly necessary cookies and local storage: chosen language and cookie consent. Not used for advertising or profiling.",
        },
        {
          title: "Stripe payments",
          body: "If you pay a deposit or balance, Stripe may set its own technical cookies on payment pages. See Stripe's policy for details.",
        },
        {
          title: "Management",
          body: "You can clear browser data at any time. Refusing non-essential cookies does not block browsing; the booking form remains available.",
        },
      ],
    },
    terms: {
      title: "Stay conditions",
      sections: [
        {
          title: "Booking",
          body: "An online request holds dates provisionally. The stay is firm once the host confirms. Maximum capacity: 6 guests. Stay from 2 to 21 nights.",
        },
        {
          title: "Rate & payment",
          body: "Single nightly rate for the whole yacht. 15% deposit after confirmation, paid by card (Stripe). Balance due 60 days before arrival, also by card. Except for force majeure, the deposit is non-refundable.",
        },
        {
          title: "Arrival & departure",
          body: "Arrival between 16:00 and 20:00. Departure between 08:00 and 11:00. Other times on written request.",
        },
        {
          title: "House rules",
          body: "Non-smoking. No pets. The yacht does not sail during the stay. Please respect neighbours and the facilities on board.",
        },
        {
          title: "Cancellation",
          body: "Cancellations must be notified by email. Depending on timing and reason (including force majeure), the host will confirm how the deposit and any balance paid are handled.",
        },
      ],
    },
  },
  admin: fr.admin,
};

export const dictionaries = { fr, nl, en };
export type Lang = keyof typeof dictionaries;

export function localeFor(lang: Lang): string {
  if (lang === "nl") return "nl-BE";
  if (lang === "en") return "en-GB";
  return "fr-BE";
}
