export const property = {
  name: "L'évasion",
  address: "Grande Drève 1",
  locality: "Ladeuze",
  postalCode: "7950",
  region: "Chièvres",
  country: "Belgique",
  email: "evasionyacht@hotmail.com",
  phone: "+32 491 86 58 09",
  phoneHref: "tel:+32491865809",
  license: "BE1023606158",
  operator: "Grégory Nicodème",
  lat: 50.56945,
  lng: 3.770154,
  maxGuests: 6,
  minNights: 2,
  maxNights: 21,
  nightlyRateCents: 14400,
  babyCotPerNightCents: 1500,
  depositPercent: 15,
  balanceDaysBefore: 60,
  checkIn: "16:00",
  checkInUntil: "20:00",
  checkOutFrom: "08:00",
  checkOut: "11:00",
  facebook: "https://www.facebook.com/profile.php?id=61576999498424",
  instagram: "https://www.instagram.com/evasionyacht",
  maps: "https://www.google.com/maps?q=50.56945,3.770154",
} as const;

export const photos = [
  { src: "/photos/07.jpg", alt: "Le yacht illuminé au bord du canal, le soir" },
  { src: "/photos/02.jpg", alt: "Le yacht amarré, reflet dans le canal" },
  { src: "/photos/01.jpg", alt: "L'avant du yacht, vu du quai" },
  { src: "/photos/06.jpg", alt: "La halte nautique et la pelouse le long de l'eau" },
  { src: "/photos/08.jpg", alt: "Le canal et le chemin de halage devant le yacht" },
  { src: "/photos/09.jpg", alt: "Pelouse, table de pique-nique et pont arrière" },
  { src: "/photos/12.jpg", alt: "Coin repas dehors, le soir, sous les guirlandes" },
  { src: "/photos/05.jpg", alt: "Le pont couvert, avec ses fauteuils" },
  { src: "/photos/11.jpg", alt: "Vue sur le canal depuis le pont" },
  { src: "/photos/03.jpg", alt: "Une des chambres doubles, sous le hublot" },
  { src: "/photos/04.jpg", alt: "Le salon du yacht" },
  { src: "/photos/10.jpg", alt: "La table du salon, face aux baies vitrées" },
] as const;
